### ISSUE TITLE
Comments to CDA-CH EMED for ballot

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/hl7ch-cda#16]
Whole Document

See notes directly in the PDF.

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
[220729-cda-ch-emed-oe.pdf](https://github.com/hl7ch/hl7ch-cda/files/9510766/220729-cda-ch-emed-oe.pdf)

**Comment by ziegm** [comment]
@pjolo 
Kann diese Issue geschlossen werden, da es das PDF selbst betrifft?

**Comment by pjolo** [comment]
Ja, kann geschlossen werden
