### ISSUE TITLE
Missing Definition of must-support (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/hl7ch-cda#17]
-

See Issue #33 in art-decor for CDA-CH EMED:

	
Finding:
hl7:manufactureMaterial.code has a description 

R	Must support. The element SHALL be present and describes the code of the medication package (GTIN) or the drug classification (WHO ATC). The @nullFlavor "NA" for magistral preparations is currently disallowed.

it is nowhere defined (or I can't find it) what the meaning of must support is for the CDA CH EMED specification. For the CH-EMED specification the meaning of must support is defined here:

http://fhir.ch/ig/ch-emed/index.html#mustsupport

MustSupport
For all elements listed in the minimum data set in the IPAG report  the corresponding FHIR elements ‘mustSupport’ flag have been set to true. ‘MustSupport’ flags are currently only defined for the Medication Card document.

Meaning of the Flag MustSupport for this Implementation Guide
The flag mustSupport follows the IHE use of R2 as defined in Appendix Z. It demands that the content creator must support these elements if they are known. If the sending application has data for the element, it is required to populate the element with a non-empty value. If the value is not known, the element may be omitted. A receiving application may ignore the information conveyed by the element. A receiving application shall not raise an error solely due to the presence or absence of the element.

Suggestion:
Define the meaning of must-support, harmonize it with CH-EMED.

Further explanation:
Raised as an issue in the current ballot for CDA-CH EMED.

Oliver Egger, ahdis ag

**Comment by ziegm** [comment]
@pjolo 
Kann diese Issue geschlossen werden?

**Comment by pjolo** [comment]
Kann geschlossen werden
