### ISSUE TITLE
Unstructured dosage: allow start and end date on dosage (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/hl7ch-cda#18]
Allow start and end date on unstructured dosage.
-> According to CH EMED issue: https://github.com/hl7ch/ch-emed/issues/127

**Comment by ziegm** [comment]
@pjolo 
Kann diese Issue geschlossen werden, da es in CH EMED behandelt wird?

**Comment by pjolo** [comment]
Ja, kann geschlossen werden.
