### ISSUE TITLE
Gender (Gabriel Hess, I4MI / BFH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/hl7ch-cda#19]
Titelei (PDF-Seite 5)

"Gleichstellung von Mann und Frau
Im Interesse einer besseren Lesbarkeit wird auf die konsequente gemeinsame Nennung der männlichen und weibli- chen Form verzichtet. Wo nicht anders angegeben, sind immer beide Geschlechter gemeint."
-> "beide Geschlechter" ist nicht inklusiv (und auch nicht konsistent mit dem Valueset für AdministrativeGender wie z.B. beim CH Patient verwendet, das aus male/female/other/unknown besteht

Gabriel Hess, I4MI / BFH

**Comment by ziegm** [comment]
@pjolo 
Kann diese Issue geschlossen werden, da es das PDF selbst betrifft?

**Comment by pjolo** [comment]
Kann geschlossen werden
