### ISSUE TITLE
Links in Inhaltsverzeichnis sind falsch (Gabriel Hess, I4MI / BFH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/hl7ch-cda#20]
V / VI

Die Seitenzahlen im Inhaltsverzeichnis sind zwar klickbar, führen aber nicht auf die korrekten Seiten.

Gabriel Hess, I4MI / BFH

**Comment by ziegm** [comment]
@pjolo 
Kann diese Issue geschlossen werden, da es das PDF selbst betrifft?

**Comment by pjolo** [comment]
Kann geschlossen werden
