### ISSUE TITLE
feedback from ipag

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/hl7ch-cda#21]
[Antwort IPAG.docx](https://github.com/hl7ch/hl7ch-cda/files/9683292/Antwort.IPAG.docx)

Dominik Aronsky und Reinhold Sojer haben seitens IPAG eHealth zum CDA-CH-EMED eine Rückmeldung verfasst im beiliegenden Worddokument.

**Comment by ziegm** [comment]
Die Issues welche im oben genannten Worddokument erfasst wurden, werden in einzelne GitHub-Issues aufgeteilt. Die Kommentare in den Klammern beziehen sich auf die Auflösung des Ballots CH EMED (FHIR):
* use case/example
   * #22 
   * #38 
* documents
   * #23 
   * #24
   * #25 
   * #26 
* documentation
   * #27 
   * #28 
   * #29 
   * #30 
   * #32 
   * #33 
   * #36
   * #39 
   * #40 
* specification 
   * #31 
* repeated dispense (prescription)
   * #34 
* medication 
   * #35 
   * #41 
* terminology
   * #37
