### ISSUE TITLE
IPAG: Unterschied Medikationsliste und -plan unklar beschrieben

### ISSUE THREAD

**Issue by ziegm** [hl7ch/hl7ch-cda#24]
![image](https://user-images.githubusercontent.com/32767151/198248014-e39b04f9-82de-4ccd-81fa-016ec4999d12.png)

**Comment by ziegm** [comment]
Im FHIR IG werden unten abgebildete Formulierungen genutzt. 

[Medication List document](http://build.fhir.org/ig/hl7ch/ch-emed/medication-list-document.html):
The Medication List document aims to fully comprise the current medication of a patient. It consists of Medication Treatment Plan, Medication Prescription, Medication Dispense and Pharmaceutical Advice entries.
- [IPAG report](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/2017/D/170607_Bericht_eMedikation_IPAG.pdf): eCurrentMedication
- [IHE Pharmacy Technical Framework Supplement: Community Medication List (PML)](https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_PML.pdf)

[Medication Card document](http://build.fhir.org/ig/hl7ch/ch-emed/medication-card-document.html):
The Medication Card document describes the current medication of a patient, medications (MORE) that have been, is or will be taken by the patient.
- [IPAG report](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/2017/D/170607_Bericht_eMedikation_IPAG.pdf): eCurrentMedication, different view
- [IHE Pharmacy Technical Framework Supplement: Community Medication List (PML)](https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_PML.pdf)

**Comment by ziegm** [comment]
Evtl. könnte man die Beschreibungen noch mit Inputs aus dem ([Factsheet eHS](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/D/factsheet-emedikation.pdf)) ergänzen:
- LIST: The Medication List document aims to fully comprise the **past and** current medication of a patient. It consists of **the current and previous** Medication Treatment Plan, Medication Prescription, Medication Dispense and Pharmaceutical Advice entries.

- CARD: The Medication Card document provides as complet an overview as possible of a patient's medication. The medications (MORE) the patient has taken, is taking or will take.

**Comment by ziegm** [comment]
Folgendes besprochen (PJ/OE/MZ):
@pjolo Formulierung in Englisch überprüfen. 
@ziegm Anpassung im FHIR IG anschliessend.

**Comment by pjolo** [comment]
Rückmeldung IPAG:
Medication List Definition ist korrekt.

Medication Card ist nur die aktuelle Medikation (ohne alte Medikation) und der verschriebenen Medikation gemäss Definition eHealth Suisse. Es beinhaltet keine historischen Information. 

Definition von CARD nicht korrekt: Nicht «the patient has taken» - die Historie ist nicht Teil des Medication Card Documents. Es besser nur die FIHR-Definition genau zu beschreiben (ohne Referenz zu IPAG oder IHE). Bitte explizit beschreiben, dass der Term Medikationsliste und Medikationsplan unterschiedliche Konzepte sind.

**Comment by pjolo** [comment]
@ziegm Final formulation:

- LIST: The Medication List document aims to fully comprise the past and current medication of a patient. It consists of the current and previous Medication Treatment Plan, Medication Prescription, Medication Dispense and Pharmaceutical Advice entries.

- CARD: The Medication Card document provides as complete an overview as possible of the current medication (MORE) that a patient is taking or should be taking.

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:
* [Medication List document](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issuecda24_card-list/medication-list-document.html)
* [Medication Card document](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issuecda24_card-list/medication-card-document.html)
* [Change Log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issuecda24_card-list/changelog.html)

**Comment by pjolo** [comment]
Ok issue can be closed
