### ISSUE TITLE
IPAG: PRE - hl7:performer als Pflichtfeld?

### ISSUE THREAD

**Issue by ziegm** [hl7ch/hl7ch-cda#31]
![image](https://user-images.githubusercontent.com/32767151/198264659-9396145a-7a59-46f2-b163-c0dea39b7b78.png)

**Comment by ziegm** [comment]
Dieses Element wird nicht im FHIR Austauschformat gemappt.
Im Austauschformat werden die verschiedenen Autoren (document/medical decision) beschrieben, siehe [Guidance](https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/different-authors.html).
Im IPAG Bericht ([Mapping Tabelle](https://docs.google.com/spreadsheets/d/1Ui3NGFE2I8yiOlHELk-B0Pke2l9-Jbe5BTeYOnS8-uE/edit#gid=0)) werden diese Angaben nicht beschrieben.

Reicht diese Erklärung oder was wäre das Mapping von hl7:documentationOf.hl7:serviceEvent.hl7:performer?

**Comment by pjolo** [comment]
Rückmeldung IPAG:
Im Fall eines Rezepts gibt es nur einen Author (verschreibende Person, einschliesslich Praxisadresse gemäss Vorgabe HMG). Dies gilt nur für die Indikationsstellung und das Rezept. Alle anderen Dokumente müssen delegiert werden können, z. B. Pharmaassistentin gibt Medikment ab im Auftrag des Apothekers. Beide müssen erfasst werden können, wo geschieht das. Bitte mit Apothekern klären, ob der Performer gemapped werden soll, allenfalls auch eine juristische Frage. Auf ärztlicher Seite braucht es das nicht, es gibt nur einen Author.

**Comment by ziegm** [comment]
Telco 17.11.022 PJ/OE/MZ:
Da das CDA-Element hl7:performer nicht im FHIR-Austauschformat gemappt wird, kann das für eine nächste Version gegebenenfalls evaluiert werden.
