### ISSUE TITLE
IPAG: DIS entry - Anzahl Packungen

### ISSUE THREAD

**Issue by ziegm** [hl7ch/hl7ch-cda#40]
![image](https://user-images.githubusercontent.com/32767151/198267965-ff27ef10-8ac8-4ea9-a680-27686ea888a1.png)

**Comment by ziegm** [comment]
CDA: hl7:supply.hl7:quantity
FHIR: MedicationDispense.quantity 1..1 ([Profil](http://build.fhir.org/ig/hl7ch/ch-emed/StructureDefinition-ch-emed-medicationdispense.html)) = Number of packages

Der Text ist so nicht vorhanden in der FHIR-Spezifikation.
Die Anzahl Packungen ist bei einer Abgabe bekannt. In FHIR wird nur noch die Anzahl Packungen angegeben.
Die Packungsgrösse wird mit Medication.amount angegeben.

Entscheid Issue zu schliessen (PJ/OE/MZ)

**Comment by pjolo** [comment]
Rückmeldung IPAG:
Empfehlen, dies mit den Apothekern nochmals abzulären (z. B. Jens Apel). Es gibt Situation, in denen die Medikamente gemäss verordnete Menge nicht vorrätig sind und somit Medikamente mit niedrigerer Dosierung in der entsprechenden Menge abgegeben werden (z. B. doppelte Anzahl Packungen). Keine Implikation auf das Rezept.

**Comment by ziegm** [comment]
17.11.2022 Telco PJ/OE/MZ:
Die Anzahl Packungen ist bei einer Abgabe bekannt. In FHIR wird nur noch die Anzahl Packungen angegeben. 
Die niedrigere Dosierung würde eine andere GTIN bedeuten, was in dem Medication Dispense document abgebildet wird.
@pjolo Check mit Jens Apel.
